# Generated by Django 5.0.2 on 2025-08-17 10:57

import api.models.complaint
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_create_default_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="status",
            field=models.ForeignKey(
                blank=True,
                default=api.models.complaint.get_default_status,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="complaints",
                to="api.complaintstatus",
            ),
        ),
    ]
